### ISSUE TITLE
Do Android builds work?

### ISSUE THREAD

**Issue by massimiliano-mantione** [steverichey/HotButteredChaos#1]
Sorry for opening this issue, I just sow this project and wanted to know if you actually *did* get android builds working on a remote headless server.

I am stuck with "Switching to AndroidPlayer is disabled" errors, and a "BuildPlayer failure: Building a player for 'Android' (13) target is not supported in this Unity build." exception message.

I sow this post:
https://forum.unity3d.com/threads/building-a-player-for-android-13-target-is-not-supported-in-this-unity-build.416598/

but using VNC is not an option in my case.

I tried adding these to my scripts:
		EditorPrefs.SetString ("AndroidSdkRoot", "/android");
		EditorPrefs.SetString ("JdkPath", "/usr/lib/jvm/java-8-openjdk-amd64");
(which is where the sdk and jdk actually are)
but it did not help.

Did it work for you?
If yes, how?

**Comment by steverichey** [comment]
It sounds like your remote server doesn't have Unity's Android module? We ended up using a Mac Mini as our build server, so it was easy enough to screen share in and set up Unity using the GUI at first, adding license info and the like. Subsequent builds were headless.

I'm guessing you'd have to find a way to download the Unity Android module using the command line. Maybe you could watch network traffic while installing Unity on your own machine to get the location of that resource. You'd probably still need to verify your license info with Unity, which might be possible via the command line, but I've never tried it.

**Comment by massimiliano-mantione** [comment]
Just as a followup... thanks for your reply, but the error seemed to be docker-related or something similar.
I now have an identical setup running in a VM (not a container) and it works.
Go figure...
